#import = ["/home/vezono/.config/alacritty/theme.toml"]

[cursor.style]
blinking = "Off"
shape = "Beam"

[font]
size = 10.50

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[window]
dynamic_padding = true

[window.padding]
x = 15
y = 15
