#! /bin/sh
feh --bg-fill ~/Media/Wallpapers/minimal.jpg
setxkbmap -layout us,ua -option "grp:lalt_lshift_toggle"

export _JAVA_AWT_WM_NONREPARENTING=1
export AWT_TOOLKIT=MToolkit
wmname VezonoBSPWM

export QT_QPA_PLATFORMTHEME="qt5ct"
export QT_STYLE_OVERRIDE=kvantum

killall -q swhks
sudo killall -q swhkd

pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/bspwm/sxhkdrc &

bspc monitor -d I II III IV V VI VII VIII IX

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Screenkey manage=off
bspc rule -a Lua5.1 state=floating center=true

#alacritty &
picom &
#spectacle -fb &
polybar -c ~/.config/bspwm/polybar/config.ini &
nm-applet &
dunst &
~/scripts/dunst_battery.sh 10 &
nextcloud &
