# Key Bindings
# key name refer to `xev` or `wev` command output,
# mod keys name: super,ctrl,alt,shift,none

# reload config
bind=SUPER+SHIFT,r,reload_config

# reload waybar
bind=SUPER+SHIFT,p,spawn_shell,usertree d waybar && usertree u waybar

# menu, terminal and lock
bind=SUPER,t,spawn,footclient
bind=SUPER,r,spawn,fuzzel --config=/home/vezono/.config/mango/fuzzel/fuzzel.ini
bind=SUPER,l,spawn,swaylock

# Clipboard history and wipe
bind=SUPER,v,spawn_shell,cliphist -db-path "$XDG_RUNTIME_DIR"/cliphist list | fuzzel --config=/home/vezono/.config/mango/fuzzel/fuzzel.ini --dmenu --with-nth 2 --width 60 | cliphist -db-path "$XDG_RUNTIME_DIR"/cliphist decode | wl-copy
bind=SUPER+SHIFT,v,spawn_shell,cliphist -db-path "$XDG_RUNTIME_DIR"/cliphist wipe && notify-send "Cliphist wiped"

# apps
bind=SUPER+SHIFT,z,spawn,pavucontrol
bind=SUPER,m,spawn,Telegram
bind=SUPER,b,spawn,firefox
bind=SUPER,e,spawn,dolphin

# controls
bind=None,XF86AudioMicMute,spawn,microphone-control toggle
bind=ctrl,Print,spawn_shell,grim -t ppm - | satty --filename - --fullscreen
bind=None,Print,spawn_shell,grim -t ppm - | satty --filename - --fullscreen --init-tool crop -d --actions-on-enter save-to-clipboard --actions-on-escape save-to-clipboard --early-exit --copy-command wl-copy

# exit
bind=SUPER+SHIFT,q,quit
bind=SUPER,q,killclient,

# switch window focus
bind=SUPER,Tab,focusstack,next
bind=SUPER,Left,focusdir,left
bind=SUPER,Right,focusdir,right
bind=SUPER,Up,focusdir,up
bind=SUPER,Down,focusdir,down

# swap window
bind=SUPER+SHIFT,Up,exchange_client,up
bind=SUPER+SHIFT,Down,exchange_client,down
bind=SUPER+SHIFT,Left,exchange_client,left
bind=SUPER+SHIFT,Right,exchange_client,right

# switch window status
bind=SUPER,g,toggleglobal,
bind=ALT,Tab,toggleoverview,
bind=SUPER+SHIFT,f,togglefloating,
bind=SUPER+SHIFT,n,togglemaximizescreen,
bind=SUPER+SHIFT,m,togglefullscreen,
bind=ALT+SHIFT,f,togglefakefullscreen,
#bind=SUPER,o,toggleoverlay,
#bind=ALT,z,toggle_scratchpad

# scroller layout
#bind=ALT,e,set_proportion,1.0
#bind=ALT,x,switch_proportion_preset,

# switch layout
#bind=SUPER,n,switch_layout

# tag switch

bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,9,view,9,0

# tag: move client to the tag and focus it
# tagsilent: move client to the tag and not focus it
# bind=Alt,1,tagsilent,1
bind=SUPER+SHIFT,1,tagsilent,1,0
bind=SUPER+SHIFT,2,tagsilent,2,0
bind=SUPER+SHIFT,3,tagsilent,3,0
bind=SUPER+SHIFT,4,tagsilent,4,0
bind=SUPER+SHIFT,5,tagsilent,5,0
bind=SUPER+SHIFT,6,tagsilent,6,0
bind=SUPER+SHIFT,7,tagsilent,7,0
bind=SUPER+SHIFT,8,tagsilent,8,0
bind=SUPER+SHIFT,9,tagsilent,9,0

# monitor switch
bind=alt+shift,Left,focusmon,left
bind=alt+shift,Right,focusmon,right
bind=SUPER+Alt,Left,tagmon,left
bind=SUPER+Alt,Right,tagmon,right

# gaps
bind=ALT+SHIFT,X,incgaps,1
bind=ALT+SHIFT,Z,incgaps,-1
bind=ALT+SHIFT,R,togglegaps

# movewin
#bind=CTRL+SHIFT,Up,movewin,+0,-50
#bind=CTRL+SHIFT,Down,movewin,+0,+50
#bind=CTRL+SHIFT,Left,movewin,-50,+0
#bind=CTRL+SHIFT,Right,movewin,+50,+0

# resizewin
#bind=CTRL+ALT,Up,resizewin,+0,-50
#bind=CTRL+ALT,Down,resizewin,+0,+50
#bind=CTRL+ALT,Left,resizewin,-50,+0
#bind=CTRL+ALT,Right,resizewin,+50,+0

# Mouse Button Bindings
# NONE mode key only work in ov mode
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize
#mousebind=NONE,btn_left,toggleoverview,1
#mousebind=NONE,btn_right,killclient,0

# Axis Bindings
axisbind=SUPER,UP,viewtoleft_have_client
axisbind=SUPER,DOWN,viewtoright_have_client
